[package]
name = "faf-rust-replayserver"
version = "0.1.0"
authors = ["Igor Kotrasinski <i.kotrasinsk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.futures]
version = "0.3.8"

[dependencies.signal-hook]
version = "0.3.0"

[dependencies.log]
version = "0.4.11"

[dependencies.env_logger]
version = "0.8.2"

[dependencies.thiserror]
version = "1.0.22"

[dependencies.async-stream]
version = "0.3.0"

[dependencies.tokio]
version = "1.0.1"
features = ["sync", "net", "io-util", "rt", "macros", "test-util", "time"]

[dependencies.tokio-util]
version = "0.6.0"

[dependencies.weak-table]
version = "0.3.0"

[dev-dependencies]
faux = "0.0.7"
