[package]
name = "faf-rust-replayserver"
version = "0.1.0"
authors = ["Igor Kotrasinski <i.kotrasinsk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.async-std]
version = "1.6"
features = ["attributes"]

[dependencies.futures]
version = "0.3.8"

[dependencies.async-channel]
version = "1.5.1"

[dependencies.stop-token]
version = "0.1.2"
features = ["unstable"]

[dependencies.signal-hook]
version = "0.1.16"

[dependencies.log]

[dependencies.env_logger]
version = "0.8.2"
